import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

# Scraper settings
SCRAPE_TIMEOUT = 30
HEADLESS_MODE = True
MAX_PAGES_TO_SCRAPE = 15
FETCH_FULL_JOB_DETAILS = False

# Company URLs
COMPANIES = {
    'Amazon': {
        'url': 'https://www.amazon.jobs/en/search?base_query=&loc_query=India&type=area&longitude=77.21676&latitude=28.63141&country=IND',
        'scraper': 'amazon'
    },
    'AWS': {
        'url': 'https://www.amazon.jobs/en/search?offset=0&result_limit=10&sort=relevant&business_category%5B%5D=amazon-web-services&distanceType=Mi&radius=24km&latitude=&longitude=&loc_group_id=&loc_query=India&base_query=&city=&country=IND&region=&county=&query_options=&',
        'scraper': 'aws'
    },
    'Accenture': {
        'url': 'https://www.accenture.com/in-en/careers/jobsearch?ct=Ahmedabad%7CBengaluru%7CBhubaneswar%7CChennai%7CCoimbatore%7CGandhinagar%7CGurugram%7CHyderabad%7CIndore%7CJaipur%7CKochi%7CKolkata%7CMumbai%7CNagpur%7CNavi%20Mumbai%7CNew%20Delhi%7CNoida%7CPune%7CThiruvananthapuram',
        'scraper': 'accenture'
    },
    'JLL': {'url': 'https://jll.wd1.myworkdayjobs.com/en-GB/jllcareers', 'scraper': 'jll'},
    'Bain': {'url': 'https://www.bain.com/careers/find-a-role/?filters=offices(275,276,274)%7C', 'scraper': 'bain'},
    'BCG': {'url': 'https://careers.bcg.com/global/en/search-results?rk=page-targeted-jobs-page54-prod-ds-Nusa6pGk&sortBy=Most%20relevant', 'scraper': 'bcg'},
    'Infosys': {'url': 'https://career.infosys.com/jobs?companyhiringtype=IL&countrycode=IN', 'scraper': 'infosys'},
    "L'Oreal": {'url': 'https://careers.loreal.com/en_US/jobs/SearchJobs/?3_110_3=18031', 'scraper': 'loreal'},
    'Mahindra': {'url': 'https://jobs.mahindracareers.com/search/?createNewAlert=false&q=&locationsearch=', 'scraper': 'mahindra'},
    'Marico': {'url': 'https://marico.sensehq.com/careers', 'scraper': 'marico'},
    'Meta': {'url': 'https://www.metacareers.com/jobs?offices[0]=Mumbai%2C%20India&offices[1]=Gurgaon%2C%20India&offices[2]=Bangalore%2C%20India', 'scraper': 'meta'},
    'Microsoft': {'url': 'https://jobs.careers.microsoft.com/global/en/search?l=en_us&pg=1&pgSz=20&o=Relevance&flt=true&ref=cms&lc=India', 'scraper': 'microsoft'},
    'Morgan Stanley': {'url': 'https://morganstanley.eightfold.ai/careers?query=&location=India&pid=549795398771&sort_by=relevance', 'scraper': 'morganstanley'},
    'Nestle': {'url': 'https://www.nestle.in/jobs/search-jobs?keyword=&country=IN', 'scraper': 'nestle'},
    'Nvidia': {'url': 'https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?Location_Country=bc33aa3152ec42d4995f4791a106ed09', 'scraper': 'nvidia'},
    'Samsung': {'url': 'https://sec.wd3.myworkdayjobs.com/Samsung_Careers?locations=0c974e8c1228010867596ab21b3c3469', 'scraper': 'samsung'},
    'Swiggy': {'url': 'https://careers.swiggy.com/#/careers?src=careers', 'scraper': 'swiggy'},
    'TCS': {'url': 'https://ibegin.tcs.com/iBegin/jobs/search', 'scraper': 'tcs'},
    'Tata Consumer': {'url': 'https://careers.tataconsumer.com/search/?createNewAlert=false&q=&locationsearch=India', 'scraper': 'tataconsumer'},
    'Tech Mahindra': {'url': 'https://careers.techmahindra.com/Currentopportunity.aspx#Advance', 'scraper': 'techmahindra'},
    'Varun Beverages': {'url': 'https://rjcorphcm-iacbiz.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/jobs?location=India&locationId=300000000489931&locationLevel=country&mode=location', 'scraper': 'varunbeverages'},
    'Wipro': {'url': 'https://careers.wipro.com/search/?q=&locationsearch=India&searchResultView=LIST', 'scraper': 'wipro'},
    'PepsiCo': {'url': 'https://www.pepsicojobs.com/main/jobs?stretchUnit=MILES&stretch=10&location=India&woe=12&regionCode=IN', 'scraper': 'pepsico'},
    'BookMyShow': {'url': 'https://bookmyshow.hire.trakstar.com/', 'scraper': 'bookmyshow'},
    'Abbott': {'url': 'https://www.jobs.abbott/us/en/search-results?qcountry=India', 'scraper': 'abbott'},
    'Airbus': {'url': 'https://ag.wd3.myworkdayjobs.com/Airbus?locationCountry=c4f78be1a8f14da0ab49ce1162348a5e', 'scraper': 'airbus'},
    'Shell': {'url': 'https://shell.wd3.myworkdayjobs.com/en-GB/shellcareers?source=APPLICANT_SOURCE_India_Local_Page&locationCountry=c4f78be1a8f14da0ab49ce1162348a5e', 'scraper': 'shell'},
    'Agilent Technologies': {'url': 'https://agilent.wd5.myworkdayjobs.com/en-GB/Agilent_Careers?locationCountry=c4f78be1a8f14da0ab49ce1162348a5e', 'scraper': 'agilent'},
    'Cadence': {'url': 'https://cadence.wd1.myworkdayjobs.com/External_Careers?Location_Country=c4f78be1a8f14da0ab49ce1162348a5e', 'scraper': 'cadence'},
    'R1 RCM': {'url': 'https://r1rcm.wd1.myworkdayjobs.com/R1RCM?Location_Country=c4f78be1a8f14da0ab49ce1162348a5e', 'scraper': 'r1rcm'},
    'Suncor Energy': {'url': 'https://suncor.wd1.myworkdayjobs.com/Suncor_External', 'scraper': 'suncor'},
    'Amara Raja Group': {'url': 'https://amararajacareers.peoplestrong.com/job/joblist', 'scraper': 'amararaja'},
    'Bajaj Finserv': {'url': 'https://bflcareers.peoplestrong.com/job/joblist', 'scraper': 'bajajfinserv'},
    'HDFC Ergo': {'url': 'https://hdfcergocareers.peoplestrong.com/job/joblist', 'scraper': 'hdfcergo'},
    'RBL Bank': {'url': 'https://rblcareers.peoplestrong.com/job/joblist', 'scraper': 'rblbank'},
    'Star Health Insurance': {'url': 'https://starhealthcareers.peoplestrong.com/job/joblist', 'scraper': 'starhealth'},
    'Zensar Technologies': {'url': 'https://fa-etvl-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/jobs?lastSelectedFacet=LOCATIONS&selectedLocationsFacet=300000000435151%3B300000000389881%3B300000000435178%3B300000000435310%3B300000000435430', 'scraper': 'zensar'},
    'Berger Paints': {'url': 'https://iabiiz.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/jobs', 'scraper': 'bergerpaints'},
    'Black Box': {'url': 'https://eoje.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs?location=India&locationId=300000000385390&locationLevel=country&mode=location', 'scraper': 'blackbox'},
    'Croma': {'url': 'https://fa-eryk-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs?location=India&locationId=300000000446243&locationLevel=country&mode=location', 'scraper': 'croma'},
    'Quess Corp': {'url': 'https://fa-eumz-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/jobs?location=India&locationId=300000000433655&locationLevel=country&mode=location', 'scraper': 'quesscorp'},
    'Tata Capital': {'url': 'https://eofh.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_3001/jobs?location=India&locationId=300000000378365&locationLevel=country&mode=location', 'scraper': 'tatacapital'},
    'Tata Chemicals': {'url': 'https://fa-eskj-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs?mode=location', 'scraper': 'tatachemicals'},
    'Tata Play': {'url': 'https://hcoe.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/jobs?mode=location', 'scraper': 'tataplay'},
    'Hexaware Technologies': {'url': 'https://jobs.hexaware.com/#en/sites/CX_1/jobs?mode=location', 'scraper': 'hexaware'},
    'Vedanta': {'url': 'https://vhr.darwinbox.in/ms/candidate/careers', 'scraper': 'vedanta'},
    'Brigade Group': {'url': 'https://brigadegroup.darwinbox.in/ms/candidatev2/main/careers/allJobs', 'scraper': 'brigadegroup'},
    'Asahi Glass': {'url': 'https://ais.darwinbox.in/ms/candidatev2/main/careers/allJobs', 'scraper': 'asahiglass'},
    'Niva Bupa': {'url': 'https://disha.darwinbox.in/ms/candidatev2/main/careers/allJobs', 'scraper': 'nivabupa'},
    'Jindal Saw': {'url': 'https://jslhrms.darwinbox.in/ms/candidatev2/main/careers/allJobs', 'scraper': 'jindalsaw'},
    'Skoda VW': {'url': 'https://skoda-vw.darwinbox.in/ms/candidate/careers', 'scraper': 'skodavw'},
    'Polycab': {'url': 'https://polycab.darwinbox.in/ms/candidate/careers', 'scraper': 'polycab'},
    'Go Digit': {'url': 'https://godigit.darwinbox.in/ms/candidatev2/main/careers/allJobs', 'scraper': 'godigit'},
    'TVS Motor': {'url': 'https://tvsmsampark.darwinbox.in/ms/candidatev2/main/careers/allJobs', 'scraper': 'tvsmotor'},
    'JSW Steel': {'url': 'https://myjsw.darwinbox.in/ms/candidatev2/main/careers/allJobs', 'scraper': 'jswsteel'},
    'GMMCO': {'url': 'https://gmmco.darwinbox.in/ms/candidate/careers', 'scraper': 'gmmco'},
    'Piramal Finance': {'url': 'https://piramalgroup.darwinbox.in/ms/candidate/careers', 'scraper': 'piramalfinance'},
    'Target': {'url': 'https://indiajobs.target.com/search-jobs?k=india&fl=1269750', 'scraper': 'target'},
    'Titan': {'url': 'https://careers.titan.in/in/en/search-results', 'scraper': 'titan'},
    'GE Aerospace': {'url': 'https://careers.geaerospace.com/global/en/search-results', 'scraper': 'geaerospace'},
    'ABB': {'url': 'https://careers.abb/global/en/search-results', 'scraper': 'abb'},
    'Allianz': {'url': 'https://careers.allianz.com/global/en/search-results?p=ChIJkbeSa_BfYzARphNChaFPjNc&location=India', 'scraper': 'allianz'},
    'Warner Bros': {'url': 'https://careers.wbd.com/global/en/search-results', 'scraper': 'warnerbros'},
    'Philips': {'url': 'https://www.careers.philips.com/in/en/search-results', 'scraper': 'philips'},
    'NTT': {'url': 'https://careers.services.global.ntt/global/en/search-results', 'scraper': 'ntt'},
    'Trane Technologies': {'url': 'https://careers.tranetechnologies.com/global/en/search-results', 'scraper': 'tranetechnologies'},
    'United Airlines': {'url': 'https://careers.united.com/us/en/search-results?keywords=India', 'scraper': 'unitedairlines'},
    'Wells Fargo': {'url': 'https://www.wellsfargojobs.com/en/jobs/?search=&country=India&pagesize=20#results', 'scraper': 'wellsfargo'},
    'AstraZeneca': {'url': 'https://careers.astrazeneca.com/location/india-jobs/7684/1269750/2', 'scraper': 'astrazeneca'},
    'SAP': {'url': 'https://jobs.sap.com/go/India/8807201/', 'scraper': 'sap'},
    'Barclays': {'url': 'https://search.jobs.barclays/search-jobs/India/13015/2/1269750/22/79/50/2', 'scraper': 'barclays'},
    'Hilton': {'url': 'https://jobs.hilton.com/apac/en/india-jobs', 'scraper': 'hilton'},
    'Marriott': {'url': 'https://careers.marriott.com/jobs?location_name=India&location_type=4', 'scraper': 'marriott'},
    'Bosch': {'url': 'https://careers.smartrecruiters.com/BoschGroup/india', 'scraper': 'bosch'},
    'Synchrony': {'url': 'https://www.synchronycareers.com/job-search-results/?location=India&country=IN&radius=25', 'scraper': 'synchrony'},
    'Air India': {'url': 'https://careers.airindia.com/search/?createNewAlert=false&q=&locationsearch=', 'scraper': 'airindia'},
    'Tata AIG': {'url': 'https://careers.tataaig.com/search/?createNewAlert=false&q=&locationsearch=', 'scraper': 'tataaig'},
    'Tata International': {'url': 'https://careers.tatainternational.com/search/?createNewAlert=false&q=&locationsearch=India', 'scraper': 'tatainternational'},
    'Tata Projects': {'url': 'https://careers.tataprojects.com/search/?createNewAlert=false&q=&optionsFacetsDD_location=&optionsFacetsDD_customfield3=&optionsFacetsDD_customfield4=&optionsFacetsDD_dept=&optionsFacetsDD_customfield1=', 'scraper': 'tataprojects'},
    'Trent': {'url': 'https://careers.trentlimited.com/search/?createNewAlert=false&q=&locationsearch=&optionsFacetsDD_dept=&optionsFacetsDD_customfield1=', 'scraper': 'trent'},
    'Bajaj Electricals': {'url': 'https://careers.bajajelectricals.com/search/?createNewAlert=false&q=&locationsearch=', 'scraper': 'bajajelectricals'},
    'Olam': {'url': 'https://careers.olamgroup.com/search/?createNewAlert=false&q=&locationsearch=India&optionsFacetsDD_customfield3=&optionsFacetsDD_customfield1=', 'scraper': 'olam'},
    'United Breweries': {'url': 'https://careers.theheinekencompany.com/India/search/?createNewAlert=false&q=&locationsearch=India', 'scraper': 'unitedbreweries'},
    'Tata Power': {'url': 'https://careers.tatapower.com/search/?createNewAlert=false&q=&locationsearch=India&optionsFacetsDD_dept=&optionsFacetsDD_customfield1=&optionsFacetsDD_customfield2=', 'scraper': 'tatapower'},
    'NatWest Group': {'url': 'https://jobs.natwestgroup.com/search/jobs/in/country/india', 'scraper': 'natwestgroup'},
    'Hitachi': {'url': 'https://careers.hitachi.com/search/jobs/in/country/india', 'scraper': 'hitachi'},
    'McKesson': {'url': 'https://careers.mckesson.com/en/search-jobs/India/733/2/1269750/22/79/50/2', 'scraper': 'mckesson'},
    'Birlasoft': {'url': 'https://jobs.birlasoft.com/go/India/684744/', 'scraper': 'birlasoft'},
    'Coforge': {'url': 'https://careers.coforge.com/coforge/', 'scraper': 'coforge'},
    'DHL': {'url': 'https://careers.dhl.com/global/en/search-results?selected_fields=%7b%22businessUnit%22:%5b%22eCommerce%20Solutions%22%5d,%22country%22:%5b%22India%22%5d%7d', 'scraper': 'dhl'},
    'Ericsson': {'url': 'https://jobs.ericsson.com/careers?page=1&jobPipeline=careersite&utm_source=ericsson.com&utm_medium=referral&utm_campaign=search_widget&start=0&pid=563121774185158&sort_by=hot', 'scraper': 'ericsson'},
    'VOIS': {'url': 'https://jobs.vodafone.com/careers?start=0&location=India&pid=563018693369050&sort_by=distance&filter_include_remote=1&filter_brand=vois', 'scraper': 'vois'},
    'Schneider Electric': {'url': 'https://careers.se.com/jobs?country=India&page=1', 'scraper': 'schneiderelectric'},
    'Siemens': {'url': 'https://jobs.siemens.com/en_US/externaljobs/SearchJobs/?42414=%5B812053%5D&42414_format=17570&listFilterMode=1&folderRecordsPerPage=6&', 'scraper': 'siemens'},
    'Deutsche Bank': {'url': 'https://careers.db.com/professionals/search-roles/#/professional/results/?country=81', 'scraper': 'deutschebank'},
    'BNP Paribas': {'url': 'https://group.bnpparibas/en/careers/all-job-offers/india', 'scraper': 'bnpparibas'},
    'BP': {'url': 'https://careers.bp.com/listing?production_bp_jobs%5BrefinementList%5D%5Blocation_list%5D%5B0%5D=India', 'scraper': 'bp'},
    'Continental': {'url': 'https://jobs.continental.com/en/#/?location=%7B%22title%22:%22India%22,%22type%22:%22country%22,%22countryCode%22:%22in%22%7D', 'scraper': 'continental'},
    'DBS Bank': {'url': 'https://www.dbs.com/careers/jobs.page?market=India', 'scraper': 'dbsbank'},
    'Novartis': {'url': 'https://www.novartis.com/in-en/careers/career-search?country%5B0%5D=LOC_IN&field_alternative_country%5B0%5D=LOC_IN', 'scraper': 'novartis'},
    'Adani Energy Solutions': {'url': 'https://www.adani.com/opportunity/#en/sites/CX_2027/jobs', 'scraper': 'adanienergy'},
    'Adani Ports': {'url': 'https://www.adani.com/opportunity/#en/sites/CX_2021/jobs', 'scraper': 'adaniports'},
    'American Tower': {'url': 'https://careers.americantower.com/#en/sites/CX_1/jobs', 'scraper': 'americantower'},
    'ANZ': {'url': 'https://careers.anz.com/search/?createNewAlert=false&q=&locationsearch=India', 'scraper': 'anz'},
    'AXA': {'url': 'https://careers.axa.com/careers-home/jobs?country=India&page=1', 'scraper': 'axa'},
    'BASF': {'url': 'https://basf.jobs/?currentPage=1&pageSize=10&addresses%2Fcountry=India', 'scraper': 'basf'},
    'Bayer': {'url': 'https://talent.bayer.com/careers?location=any&pid=562949975473181', 'scraper': 'bayer'},
    'Disney': {'url': 'https://www.disneycareers.com/en/location/india-jobs/391/1269750/2', 'scraper': 'disney'},
    'Emirates Group': {'url': 'https://www.emiratesgroupcareers.com/search-and-apply/', 'scraper': 'emiratesgroup'},
    'GSK': {'url': 'https://jobs.gsk.com/india-pharma/jobs', 'scraper': 'gsk'},
    'Hyundai': {'url': 'https://careers.hyundai.co.in/search/', 'scraper': 'hyundai'},
    'IHG': {'url': 'https://careers.ihg.com/en/search-and-apply/', 'scraper': 'ihg'},
    'Intuit': {'url': 'https://jobs.intuit.com/location/india-jobs/27595/1269750/2', 'scraper': 'intuit'},
    'Lenovo': {'url': 'https://jobs.lenovo.com/en_US/careers/SearchJobs/', 'scraper': 'lenovo'},
    'LG Electronics': {'url': 'https://lgcns.eightfold.ai/careers', 'scraper': 'lgelectronics'},
    'Mercedes-Benz': {'url': 'https://jobs.mercedes-benz.com/en', 'scraper': 'mercedesbenz'},
    'Munich Re': {'url': 'https://careers.munichre.com/en/search-jobs', 'scraper': 'munichre'},
    'Panasonic': {'url': 'https://careers.na.panasonic.com/jobs', 'scraper': 'panasonic'},
    'Prestige Group': {'url': 'https://jobs.prestigeconstructions.com/go/View-All-Jobs/9217401/', 'scraper': 'prestigegroup'},
    'Rio Tinto': {'url': 'https://jobs.riotinto.com/', 'scraper': 'riotinto'},
    'S&P Global': {'url': 'https://careers.spglobal.com/jobs', 'scraper': 'spglobal'},
    'UnitedHealth Group': {'url': 'https://careers.unitedhealthgroup.com/job-search-results/', 'scraper': 'unitedhealthgroup'},
    'Verizon': {'url': 'https://mycareer.verizon.com/jobs/', 'scraper': 'verizon'},
    'Vodafone Idea': {'url': 'https://careers.vodafoneidea.com/go/All-Current-Job-Opportunities/4268701/', 'scraper': 'vodafoneidea'},
    'Whirlpool': {'url': 'https://jobs.whirlpool.com/careers', 'scraper': 'whirlpool'},
    'Britannia Industries': {'url': 'https://britannia.turbohire.co/', 'scraper': 'britannia'},
    'BMW Group': {'url': 'https://www.bmwgroup.jobs/in/en/jobs.html', 'scraper': 'bmwgroup'},
    'Crompton Greaves': {'url': 'https://career10.successfactors.com/portalcareer?company=cromptongr', 'scraper': 'crompton'},
    'Diageo': {'url': 'https://diageo.wd3.myworkdayjobs.com/Diageo_Careers', 'scraper': 'diageo'},
    'DLF': {'url': 'https://www.dlf.in/career-page', 'scraper': 'dlf'},
    'Havells': {'url': 'https://iabgcp.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1', 'scraper': 'havells'},
    'HDFC Life': {'url': 'https://www.hdfclife.com/hdfc-careers/', 'scraper': 'hdfclife'},
    'Hindustan Aeronautics': {'url': 'https://hal-india.co.in/career', 'scraper': 'hal'},
    'Honda': {'url': 'https://www.hondacarindia.com/careers', 'scraper': 'honda'},
    'ICICI Lombard': {'url': 'https://www.icicilombard.com/careers/areas-of-opportunity', 'scraper': 'icicilombard'},
    'IndusInd Bank': {'url': 'https://www.indusind.com/in/en/personal/career.html', 'scraper': 'indusindbank'},
    'Indian Oil Corporation': {'url': 'https://iocl.com/latest-job-opening', 'scraper': 'iocl'},
    'Kajaria Ceramics': {'url': 'https://www.kajariaceramics.com/career', 'scraper': 'kajaria'},
    'Kia India': {'url': 'https://career.kiaindia.net/kiaindia/', 'scraper': 'kiaindia'},
    'Mankind Pharma': {'url': 'https://careers.mankindpharma.com/', 'scraper': 'mankindpharma'},
    'Max Healthcare': {'url': 'https://maxhealthcarecareers.peoplestrong.com/', 'scraper': 'maxhealthcare'},
    'NTPC': {'url': 'https://careers.ntpc.co.in/', 'scraper': 'ntpc'},
    'Nissan': {'url': 'https://alliance.wd3.myworkdayjobs.com/nissanjobs', 'scraper': 'nissan'},
    'OYO': {'url': 'https://careers.smartrecruiters.com/OYO', 'scraper': 'oyo'},
    'Pidilite Industries': {'url': 'https://pidilitecareers.peoplestrong.com/home', 'scraper': 'pidilite'},
    'Saint-Gobain': {'url': 'https://joinus.saint-gobain.com/en', 'scraper': 'saintgobain'},
    'Siemens Energy': {'url': 'https://jobs.siemens-energy.com/en_US/jobs/Jobs', 'scraper': 'siemensenergy'},
    'Tata Communications': {'url': 'https://jobs.tatacommunications.com/', 'scraper': 'tatacommunications'},
    'Toyota Kirloskar': {'url': 'https://www.toyotabharat.com/careers/', 'scraper': 'toyotakirloskar'},
    'Yes Bank': {'url': 'https://yesforyou.darwinbox.in/ms/candidate/careers', 'scraper': 'yesbank'},
}
